--Here you can create assets directly under assets folder then you can have autocomplete for all these and you must import assets as a rbxmx file
--Remember that this is not needed to be done but if you would like auto complete on assets then i would recomend putting them here
--Here is how you do it step by step

--[[
1- first go open roblox studio
2- second open your project where you keep your assets 
3- third right click your folder where you are keeping the assets you would like to import like gui for example
4- fourth click the save/export button and then click save to file
5- fifth write a file name for what it will be called inside vscode
6- sixth under the file name you can see export as type and click rbxmx and not rbxm
7- seventh go to your project and inside there go to Lightweight-DependencyLoader-ROBLOX-LUAU/src/assets and save your file there
8- eighth BAM your finished now luau language server will read that file and give you autocomplete for those files and rojo will also automatically add the assets to your project when rojo serve
]]
